// Code generated by cmd/cgo; DO NOT EDIT.

package scipio

import "unsafe"

import "syscall"

import _cgopackage "runtime/cgo"

type _ _cgopackage.Incomplete
var _ syscall.Errno
func _Cgo_ptr(ptr unsafe.Pointer) unsafe.Pointer { return ptr }

//go:linkname _Cgo_always_false runtime.cgoAlwaysFalse
var _Cgo_always_false bool
//go:linkname _Cgo_use runtime.cgoUse
func _Cgo_use(interface{})
//go:linkname _Cgo_keepalive runtime.cgoKeepAlive
//go:noescape
func _Cgo_keepalive(interface{})
//go:linkname _Cgo_no_callback runtime.cgoNoCallback
func _Cgo_no_callback(bool)
type _Ctype_SF_INFO = _Ctype_struct_SF_INFO

type _Ctype_SNDFILE = _Ctype_struct_sf_private_tag

type _Ctype__GoString_ string

type _Ctype___int64_t = _Ctype_long

type _Ctype_char int8

type _Ctype_double float64

type _Ctype_float float32

type _Ctype_int int32

type _Ctype_int64_t = _Ctype___int64_t

type _Ctype_intgo = _Ctype_ptrdiff_t

type _Ctype_long int64

type _Ctype_ptrdiff_t = _Ctype_long

type _Ctype_sf_count_t = _Ctype_int64_t

type _Ctype_short int16

type _Ctype_struct_SF_INFO struct {
	frames		_Ctype_sf_count_t
	samplerate	_Ctype_int
	channels	_Ctype_int
	format		_Ctype_int
	sections	_Ctype_int
	seekable	_Ctype_int
	_		[4]byte
}

type _Ctype_struct_sf_private_tag _cgopackage.Incomplete

type _Ctype_void [0]byte

//go:linkname _cgo_runtime_cgocall runtime.cgocall
func _cgo_runtime_cgocall(unsafe.Pointer, uintptr) int32

//go:linkname _cgoCheckPointer runtime.cgoCheckPointer
//go:noescape
func _cgoCheckPointer(interface{}, interface{})

//go:linkname _cgoCheckResult runtime.cgoCheckResult
//go:noescape
func _cgoCheckResult(interface{})
const _Ciconst_SEEK_CUR = 0x1
const _Ciconst_SEEK_END = 0x2
const _Ciconst_SEEK_SET = 0x0
const _Ciconst_SFM_RDWR = 0x30
const _Ciconst_SFM_READ = 0x10
const _Ciconst_SFM_WRITE = 0x20
const _Ciconst_SF_STR_ALBUM = 0x7
const _Ciconst_SF_STR_ARTIST = 0x4
const _Ciconst_SF_STR_COMMENT = 0x5
const _Ciconst_SF_STR_COPYRIGHT = 0x2
const _Ciconst_SF_STR_DATE = 0x6
const _Ciconst_SF_STR_FIRST = 0x1
const _Ciconst_SF_STR_GENRE = 0x10
const _Ciconst_SF_STR_LAST = 0x10
const _Ciconst_SF_STR_LICENSE = 0x8
const _Ciconst_SF_STR_SOFTWARE = 0x3
const _Ciconst_SF_STR_TITLE = 0x1
const _Ciconst_SF_STR_TRACKNUMBER = 0x9
const _Ciconst_SF_TRUE = 0x1


// CString converts the Go string s to a C string.
//
// The C string is allocated in the C heap using malloc.
// It is the caller's responsibility to arrange for it to be
// freed, such as by calling C.free (be sure to include stdlib.h
// if C.free is needed).
func _Cfunc_CString(s string) *_Ctype_char {
	if len(s)+1 <= 0 {
		panic("string too large")
	}
	p := _cgo_cmalloc(uint64(len(s)+1))
	sliceHeader := struct {
		p   unsafe.Pointer
		len int
		cap int
	}{p, len(s)+1, len(s)+1}
	b := *(*[]byte)(unsafe.Pointer(&sliceHeader))
	copy(b, s)
	b[len(s)] = 0
	return (*_Ctype_char)(p)
}

//go:linkname _cgo_runtime_gostring runtime.gostring
func _cgo_runtime_gostring(*_Ctype_char) string

// GoString converts the C string p into a Go string.
func _Cfunc_GoString(p *_Ctype_char) string {
	return _cgo_runtime_gostring(p)
}
//go:cgo_import_static _cgo_75cf4c0ad46f_Cfunc_free
//go:linkname __cgofn__cgo_75cf4c0ad46f_Cfunc_free _cgo_75cf4c0ad46f_Cfunc_free
var __cgofn__cgo_75cf4c0ad46f_Cfunc_free byte
var _cgo_75cf4c0ad46f_Cfunc_free = unsafe.Pointer(&__cgofn__cgo_75cf4c0ad46f_Cfunc_free)

//go:cgo_unsafe_args
func _Cfunc_free(p0 unsafe.Pointer) (r1 _Ctype_void) {
	_cgo_runtime_cgocall(_cgo_75cf4c0ad46f_Cfunc_free, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
	}
	return
}
//go:cgo_import_static _cgo_75cf4c0ad46f_Cfunc_sf_close
//go:linkname __cgofn__cgo_75cf4c0ad46f_Cfunc_sf_close _cgo_75cf4c0ad46f_Cfunc_sf_close
var __cgofn__cgo_75cf4c0ad46f_Cfunc_sf_close byte
var _cgo_75cf4c0ad46f_Cfunc_sf_close = unsafe.Pointer(&__cgofn__cgo_75cf4c0ad46f_Cfunc_sf_close)

//go:cgo_unsafe_args
func _Cfunc_sf_close(p0 *_Ctype_struct_sf_private_tag) (r1 _Ctype_int) {
	_cgo_runtime_cgocall(_cgo_75cf4c0ad46f_Cfunc_sf_close, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
	}
	return
}
//go:cgo_import_static _cgo_75cf4c0ad46f_Cfunc_sf_error_number
//go:linkname __cgofn__cgo_75cf4c0ad46f_Cfunc_sf_error_number _cgo_75cf4c0ad46f_Cfunc_sf_error_number
var __cgofn__cgo_75cf4c0ad46f_Cfunc_sf_error_number byte
var _cgo_75cf4c0ad46f_Cfunc_sf_error_number = unsafe.Pointer(&__cgofn__cgo_75cf4c0ad46f_Cfunc_sf_error_number)

//go:cgo_unsafe_args
func _Cfunc_sf_error_number(p0 _Ctype_int) (r1 *_Ctype_char) {
	_cgo_runtime_cgocall(_cgo_75cf4c0ad46f_Cfunc_sf_error_number, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
	}
	return
}
//go:cgo_import_static _cgo_75cf4c0ad46f_Cfunc_sf_format_check
//go:linkname __cgofn__cgo_75cf4c0ad46f_Cfunc_sf_format_check _cgo_75cf4c0ad46f_Cfunc_sf_format_check
var __cgofn__cgo_75cf4c0ad46f_Cfunc_sf_format_check byte
var _cgo_75cf4c0ad46f_Cfunc_sf_format_check = unsafe.Pointer(&__cgofn__cgo_75cf4c0ad46f_Cfunc_sf_format_check)

//go:cgo_unsafe_args
func _Cfunc_sf_format_check(p0 *_Ctype_struct_SF_INFO) (r1 _Ctype_int) {
	_cgo_runtime_cgocall(_cgo_75cf4c0ad46f_Cfunc_sf_format_check, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
	}
	return
}
//go:cgo_import_static _cgo_75cf4c0ad46f_Cfunc_sf_get_string
//go:linkname __cgofn__cgo_75cf4c0ad46f_Cfunc_sf_get_string _cgo_75cf4c0ad46f_Cfunc_sf_get_string
var __cgofn__cgo_75cf4c0ad46f_Cfunc_sf_get_string byte
var _cgo_75cf4c0ad46f_Cfunc_sf_get_string = unsafe.Pointer(&__cgofn__cgo_75cf4c0ad46f_Cfunc_sf_get_string)

//go:cgo_unsafe_args
func _Cfunc_sf_get_string(p0 *_Ctype_struct_sf_private_tag, p1 _Ctype_int) (r1 *_Ctype_char) {
	_cgo_runtime_cgocall(_cgo_75cf4c0ad46f_Cfunc_sf_get_string, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
		_Cgo_use(p1)
	}
	return
}
//go:cgo_import_static _cgo_75cf4c0ad46f_Cfunc_sf_open
//go:linkname __cgofn__cgo_75cf4c0ad46f_Cfunc_sf_open _cgo_75cf4c0ad46f_Cfunc_sf_open
var __cgofn__cgo_75cf4c0ad46f_Cfunc_sf_open byte
var _cgo_75cf4c0ad46f_Cfunc_sf_open = unsafe.Pointer(&__cgofn__cgo_75cf4c0ad46f_Cfunc_sf_open)

//go:cgo_unsafe_args
func _Cfunc_sf_open(p0 *_Ctype_char, p1 _Ctype_int, p2 *_Ctype_struct_SF_INFO) (r1 *_Ctype_struct_sf_private_tag) {
	_cgo_runtime_cgocall(_cgo_75cf4c0ad46f_Cfunc_sf_open, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
		_Cgo_use(p1)
		_Cgo_use(p2)
	}
	return
}
//go:cgo_import_static _cgo_75cf4c0ad46f_Cfunc_sf_open_fd
//go:linkname __cgofn__cgo_75cf4c0ad46f_Cfunc_sf_open_fd _cgo_75cf4c0ad46f_Cfunc_sf_open_fd
var __cgofn__cgo_75cf4c0ad46f_Cfunc_sf_open_fd byte
var _cgo_75cf4c0ad46f_Cfunc_sf_open_fd = unsafe.Pointer(&__cgofn__cgo_75cf4c0ad46f_Cfunc_sf_open_fd)

//go:cgo_unsafe_args
func _Cfunc_sf_open_fd(p0 _Ctype_int, p1 _Ctype_int, p2 *_Ctype_struct_SF_INFO, p3 _Ctype_int) (r1 *_Ctype_struct_sf_private_tag) {
	_cgo_runtime_cgocall(_cgo_75cf4c0ad46f_Cfunc_sf_open_fd, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
		_Cgo_use(p1)
		_Cgo_use(p2)
		_Cgo_use(p3)
	}
	return
}
//go:cgo_import_static _cgo_75cf4c0ad46f_Cfunc_sf_read_double
//go:linkname __cgofn__cgo_75cf4c0ad46f_Cfunc_sf_read_double _cgo_75cf4c0ad46f_Cfunc_sf_read_double
var __cgofn__cgo_75cf4c0ad46f_Cfunc_sf_read_double byte
var _cgo_75cf4c0ad46f_Cfunc_sf_read_double = unsafe.Pointer(&__cgofn__cgo_75cf4c0ad46f_Cfunc_sf_read_double)

//go:cgo_unsafe_args
func _Cfunc_sf_read_double(p0 *_Ctype_struct_sf_private_tag, p1 *_Ctype_double, p2 _Ctype_sf_count_t) (r1 _Ctype_sf_count_t) {
	_cgo_runtime_cgocall(_cgo_75cf4c0ad46f_Cfunc_sf_read_double, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
		_Cgo_use(p1)
		_Cgo_use(p2)
	}
	return
}
//go:cgo_import_static _cgo_75cf4c0ad46f_Cfunc_sf_read_float
//go:linkname __cgofn__cgo_75cf4c0ad46f_Cfunc_sf_read_float _cgo_75cf4c0ad46f_Cfunc_sf_read_float
var __cgofn__cgo_75cf4c0ad46f_Cfunc_sf_read_float byte
var _cgo_75cf4c0ad46f_Cfunc_sf_read_float = unsafe.Pointer(&__cgofn__cgo_75cf4c0ad46f_Cfunc_sf_read_float)

//go:cgo_unsafe_args
func _Cfunc_sf_read_float(p0 *_Ctype_struct_sf_private_tag, p1 *_Ctype_float, p2 _Ctype_sf_count_t) (r1 _Ctype_sf_count_t) {
	_cgo_runtime_cgocall(_cgo_75cf4c0ad46f_Cfunc_sf_read_float, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
		_Cgo_use(p1)
		_Cgo_use(p2)
	}
	return
}
//go:cgo_import_static _cgo_75cf4c0ad46f_Cfunc_sf_read_int
//go:linkname __cgofn__cgo_75cf4c0ad46f_Cfunc_sf_read_int _cgo_75cf4c0ad46f_Cfunc_sf_read_int
var __cgofn__cgo_75cf4c0ad46f_Cfunc_sf_read_int byte
var _cgo_75cf4c0ad46f_Cfunc_sf_read_int = unsafe.Pointer(&__cgofn__cgo_75cf4c0ad46f_Cfunc_sf_read_int)

//go:cgo_unsafe_args
func _Cfunc_sf_read_int(p0 *_Ctype_struct_sf_private_tag, p1 *_Ctype_int, p2 _Ctype_sf_count_t) (r1 _Ctype_sf_count_t) {
	_cgo_runtime_cgocall(_cgo_75cf4c0ad46f_Cfunc_sf_read_int, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
		_Cgo_use(p1)
		_Cgo_use(p2)
	}
	return
}
//go:cgo_import_static _cgo_75cf4c0ad46f_Cfunc_sf_read_short
//go:linkname __cgofn__cgo_75cf4c0ad46f_Cfunc_sf_read_short _cgo_75cf4c0ad46f_Cfunc_sf_read_short
var __cgofn__cgo_75cf4c0ad46f_Cfunc_sf_read_short byte
var _cgo_75cf4c0ad46f_Cfunc_sf_read_short = unsafe.Pointer(&__cgofn__cgo_75cf4c0ad46f_Cfunc_sf_read_short)

//go:cgo_unsafe_args
func _Cfunc_sf_read_short(p0 *_Ctype_struct_sf_private_tag, p1 *_Ctype_short, p2 _Ctype_sf_count_t) (r1 _Ctype_sf_count_t) {
	_cgo_runtime_cgocall(_cgo_75cf4c0ad46f_Cfunc_sf_read_short, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
		_Cgo_use(p1)
		_Cgo_use(p2)
	}
	return
}
//go:cgo_import_static _cgo_75cf4c0ad46f_Cfunc_sf_readf_double
//go:linkname __cgofn__cgo_75cf4c0ad46f_Cfunc_sf_readf_double _cgo_75cf4c0ad46f_Cfunc_sf_readf_double
var __cgofn__cgo_75cf4c0ad46f_Cfunc_sf_readf_double byte
var _cgo_75cf4c0ad46f_Cfunc_sf_readf_double = unsafe.Pointer(&__cgofn__cgo_75cf4c0ad46f_Cfunc_sf_readf_double)

//go:cgo_unsafe_args
func _Cfunc_sf_readf_double(p0 *_Ctype_struct_sf_private_tag, p1 *_Ctype_double, p2 _Ctype_sf_count_t) (r1 _Ctype_sf_count_t) {
	_cgo_runtime_cgocall(_cgo_75cf4c0ad46f_Cfunc_sf_readf_double, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
		_Cgo_use(p1)
		_Cgo_use(p2)
	}
	return
}
//go:cgo_import_static _cgo_75cf4c0ad46f_Cfunc_sf_readf_float
//go:linkname __cgofn__cgo_75cf4c0ad46f_Cfunc_sf_readf_float _cgo_75cf4c0ad46f_Cfunc_sf_readf_float
var __cgofn__cgo_75cf4c0ad46f_Cfunc_sf_readf_float byte
var _cgo_75cf4c0ad46f_Cfunc_sf_readf_float = unsafe.Pointer(&__cgofn__cgo_75cf4c0ad46f_Cfunc_sf_readf_float)

//go:cgo_unsafe_args
func _Cfunc_sf_readf_float(p0 *_Ctype_struct_sf_private_tag, p1 *_Ctype_float, p2 _Ctype_sf_count_t) (r1 _Ctype_sf_count_t) {
	_cgo_runtime_cgocall(_cgo_75cf4c0ad46f_Cfunc_sf_readf_float, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
		_Cgo_use(p1)
		_Cgo_use(p2)
	}
	return
}
//go:cgo_import_static _cgo_75cf4c0ad46f_Cfunc_sf_readf_int
//go:linkname __cgofn__cgo_75cf4c0ad46f_Cfunc_sf_readf_int _cgo_75cf4c0ad46f_Cfunc_sf_readf_int
var __cgofn__cgo_75cf4c0ad46f_Cfunc_sf_readf_int byte
var _cgo_75cf4c0ad46f_Cfunc_sf_readf_int = unsafe.Pointer(&__cgofn__cgo_75cf4c0ad46f_Cfunc_sf_readf_int)

//go:cgo_unsafe_args
func _Cfunc_sf_readf_int(p0 *_Ctype_struct_sf_private_tag, p1 *_Ctype_int, p2 _Ctype_sf_count_t) (r1 _Ctype_sf_count_t) {
	_cgo_runtime_cgocall(_cgo_75cf4c0ad46f_Cfunc_sf_readf_int, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
		_Cgo_use(p1)
		_Cgo_use(p2)
	}
	return
}
//go:cgo_import_static _cgo_75cf4c0ad46f_Cfunc_sf_readf_short
//go:linkname __cgofn__cgo_75cf4c0ad46f_Cfunc_sf_readf_short _cgo_75cf4c0ad46f_Cfunc_sf_readf_short
var __cgofn__cgo_75cf4c0ad46f_Cfunc_sf_readf_short byte
var _cgo_75cf4c0ad46f_Cfunc_sf_readf_short = unsafe.Pointer(&__cgofn__cgo_75cf4c0ad46f_Cfunc_sf_readf_short)

//go:cgo_unsafe_args
func _Cfunc_sf_readf_short(p0 *_Ctype_struct_sf_private_tag, p1 *_Ctype_short, p2 _Ctype_sf_count_t) (r1 _Ctype_sf_count_t) {
	_cgo_runtime_cgocall(_cgo_75cf4c0ad46f_Cfunc_sf_readf_short, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
		_Cgo_use(p1)
		_Cgo_use(p2)
	}
	return
}
//go:cgo_import_static _cgo_75cf4c0ad46f_Cfunc_sf_seek
//go:linkname __cgofn__cgo_75cf4c0ad46f_Cfunc_sf_seek _cgo_75cf4c0ad46f_Cfunc_sf_seek
var __cgofn__cgo_75cf4c0ad46f_Cfunc_sf_seek byte
var _cgo_75cf4c0ad46f_Cfunc_sf_seek = unsafe.Pointer(&__cgofn__cgo_75cf4c0ad46f_Cfunc_sf_seek)

//go:cgo_unsafe_args
func _Cfunc_sf_seek(p0 *_Ctype_struct_sf_private_tag, p1 _Ctype_sf_count_t, p2 _Ctype_int) (r1 _Ctype_sf_count_t) {
	_cgo_runtime_cgocall(_cgo_75cf4c0ad46f_Cfunc_sf_seek, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
		_Cgo_use(p1)
		_Cgo_use(p2)
	}
	return
}
//go:cgo_import_static _cgo_75cf4c0ad46f_Cfunc_sf_set_string
//go:linkname __cgofn__cgo_75cf4c0ad46f_Cfunc_sf_set_string _cgo_75cf4c0ad46f_Cfunc_sf_set_string
var __cgofn__cgo_75cf4c0ad46f_Cfunc_sf_set_string byte
var _cgo_75cf4c0ad46f_Cfunc_sf_set_string = unsafe.Pointer(&__cgofn__cgo_75cf4c0ad46f_Cfunc_sf_set_string)

//go:cgo_unsafe_args
func _Cfunc_sf_set_string(p0 *_Ctype_struct_sf_private_tag, p1 _Ctype_int, p2 *_Ctype_char) (r1 _Ctype_int) {
	_cgo_runtime_cgocall(_cgo_75cf4c0ad46f_Cfunc_sf_set_string, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
		_Cgo_use(p1)
		_Cgo_use(p2)
	}
	return
}
//go:cgo_import_static _cgo_75cf4c0ad46f_Cfunc_sf_strerror
//go:linkname __cgofn__cgo_75cf4c0ad46f_Cfunc_sf_strerror _cgo_75cf4c0ad46f_Cfunc_sf_strerror
var __cgofn__cgo_75cf4c0ad46f_Cfunc_sf_strerror byte
var _cgo_75cf4c0ad46f_Cfunc_sf_strerror = unsafe.Pointer(&__cgofn__cgo_75cf4c0ad46f_Cfunc_sf_strerror)

//go:cgo_unsafe_args
func _Cfunc_sf_strerror(p0 *_Ctype_struct_sf_private_tag) (r1 *_Ctype_char) {
	_cgo_runtime_cgocall(_cgo_75cf4c0ad46f_Cfunc_sf_strerror, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
	}
	return
}
//go:cgo_import_static _cgo_75cf4c0ad46f_Cfunc_sf_write_double
//go:linkname __cgofn__cgo_75cf4c0ad46f_Cfunc_sf_write_double _cgo_75cf4c0ad46f_Cfunc_sf_write_double
var __cgofn__cgo_75cf4c0ad46f_Cfunc_sf_write_double byte
var _cgo_75cf4c0ad46f_Cfunc_sf_write_double = unsafe.Pointer(&__cgofn__cgo_75cf4c0ad46f_Cfunc_sf_write_double)

//go:cgo_unsafe_args
func _Cfunc_sf_write_double(p0 *_Ctype_struct_sf_private_tag, p1 *_Ctype_double, p2 _Ctype_sf_count_t) (r1 _Ctype_sf_count_t) {
	_cgo_runtime_cgocall(_cgo_75cf4c0ad46f_Cfunc_sf_write_double, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
		_Cgo_use(p1)
		_Cgo_use(p2)
	}
	return
}
//go:cgo_import_static _cgo_75cf4c0ad46f_Cfunc_sf_write_float
//go:linkname __cgofn__cgo_75cf4c0ad46f_Cfunc_sf_write_float _cgo_75cf4c0ad46f_Cfunc_sf_write_float
var __cgofn__cgo_75cf4c0ad46f_Cfunc_sf_write_float byte
var _cgo_75cf4c0ad46f_Cfunc_sf_write_float = unsafe.Pointer(&__cgofn__cgo_75cf4c0ad46f_Cfunc_sf_write_float)

//go:cgo_unsafe_args
func _Cfunc_sf_write_float(p0 *_Ctype_struct_sf_private_tag, p1 *_Ctype_float, p2 _Ctype_sf_count_t) (r1 _Ctype_sf_count_t) {
	_cgo_runtime_cgocall(_cgo_75cf4c0ad46f_Cfunc_sf_write_float, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
		_Cgo_use(p1)
		_Cgo_use(p2)
	}
	return
}
//go:cgo_import_static _cgo_75cf4c0ad46f_Cfunc_sf_write_int
//go:linkname __cgofn__cgo_75cf4c0ad46f_Cfunc_sf_write_int _cgo_75cf4c0ad46f_Cfunc_sf_write_int
var __cgofn__cgo_75cf4c0ad46f_Cfunc_sf_write_int byte
var _cgo_75cf4c0ad46f_Cfunc_sf_write_int = unsafe.Pointer(&__cgofn__cgo_75cf4c0ad46f_Cfunc_sf_write_int)

//go:cgo_unsafe_args
func _Cfunc_sf_write_int(p0 *_Ctype_struct_sf_private_tag, p1 *_Ctype_int, p2 _Ctype_sf_count_t) (r1 _Ctype_sf_count_t) {
	_cgo_runtime_cgocall(_cgo_75cf4c0ad46f_Cfunc_sf_write_int, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
		_Cgo_use(p1)
		_Cgo_use(p2)
	}
	return
}
//go:cgo_import_static _cgo_75cf4c0ad46f_Cfunc_sf_write_short
//go:linkname __cgofn__cgo_75cf4c0ad46f_Cfunc_sf_write_short _cgo_75cf4c0ad46f_Cfunc_sf_write_short
var __cgofn__cgo_75cf4c0ad46f_Cfunc_sf_write_short byte
var _cgo_75cf4c0ad46f_Cfunc_sf_write_short = unsafe.Pointer(&__cgofn__cgo_75cf4c0ad46f_Cfunc_sf_write_short)

//go:cgo_unsafe_args
func _Cfunc_sf_write_short(p0 *_Ctype_struct_sf_private_tag, p1 *_Ctype_short, p2 _Ctype_sf_count_t) (r1 _Ctype_sf_count_t) {
	_cgo_runtime_cgocall(_cgo_75cf4c0ad46f_Cfunc_sf_write_short, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
		_Cgo_use(p1)
		_Cgo_use(p2)
	}
	return
}
//go:cgo_import_static _cgo_75cf4c0ad46f_Cfunc_sf_write_sync
//go:linkname __cgofn__cgo_75cf4c0ad46f_Cfunc_sf_write_sync _cgo_75cf4c0ad46f_Cfunc_sf_write_sync
var __cgofn__cgo_75cf4c0ad46f_Cfunc_sf_write_sync byte
var _cgo_75cf4c0ad46f_Cfunc_sf_write_sync = unsafe.Pointer(&__cgofn__cgo_75cf4c0ad46f_Cfunc_sf_write_sync)

//go:cgo_unsafe_args
func _Cfunc_sf_write_sync(p0 *_Ctype_struct_sf_private_tag) (r1 _Ctype_void) {
	_cgo_runtime_cgocall(_cgo_75cf4c0ad46f_Cfunc_sf_write_sync, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
	}
	return
}
//go:cgo_import_static _cgo_75cf4c0ad46f_Cfunc_sf_writef_double
//go:linkname __cgofn__cgo_75cf4c0ad46f_Cfunc_sf_writef_double _cgo_75cf4c0ad46f_Cfunc_sf_writef_double
var __cgofn__cgo_75cf4c0ad46f_Cfunc_sf_writef_double byte
var _cgo_75cf4c0ad46f_Cfunc_sf_writef_double = unsafe.Pointer(&__cgofn__cgo_75cf4c0ad46f_Cfunc_sf_writef_double)

//go:cgo_unsafe_args
func _Cfunc_sf_writef_double(p0 *_Ctype_struct_sf_private_tag, p1 *_Ctype_double, p2 _Ctype_sf_count_t) (r1 _Ctype_sf_count_t) {
	_cgo_runtime_cgocall(_cgo_75cf4c0ad46f_Cfunc_sf_writef_double, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
		_Cgo_use(p1)
		_Cgo_use(p2)
	}
	return
}
//go:cgo_import_static _cgo_75cf4c0ad46f_Cfunc_sf_writef_float
//go:linkname __cgofn__cgo_75cf4c0ad46f_Cfunc_sf_writef_float _cgo_75cf4c0ad46f_Cfunc_sf_writef_float
var __cgofn__cgo_75cf4c0ad46f_Cfunc_sf_writef_float byte
var _cgo_75cf4c0ad46f_Cfunc_sf_writef_float = unsafe.Pointer(&__cgofn__cgo_75cf4c0ad46f_Cfunc_sf_writef_float)

//go:cgo_unsafe_args
func _Cfunc_sf_writef_float(p0 *_Ctype_struct_sf_private_tag, p1 *_Ctype_float, p2 _Ctype_sf_count_t) (r1 _Ctype_sf_count_t) {
	_cgo_runtime_cgocall(_cgo_75cf4c0ad46f_Cfunc_sf_writef_float, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
		_Cgo_use(p1)
		_Cgo_use(p2)
	}
	return
}
//go:cgo_import_static _cgo_75cf4c0ad46f_Cfunc_sf_writef_int
//go:linkname __cgofn__cgo_75cf4c0ad46f_Cfunc_sf_writef_int _cgo_75cf4c0ad46f_Cfunc_sf_writef_int
var __cgofn__cgo_75cf4c0ad46f_Cfunc_sf_writef_int byte
var _cgo_75cf4c0ad46f_Cfunc_sf_writef_int = unsafe.Pointer(&__cgofn__cgo_75cf4c0ad46f_Cfunc_sf_writef_int)

//go:cgo_unsafe_args
func _Cfunc_sf_writef_int(p0 *_Ctype_struct_sf_private_tag, p1 *_Ctype_int, p2 _Ctype_sf_count_t) (r1 _Ctype_sf_count_t) {
	_cgo_runtime_cgocall(_cgo_75cf4c0ad46f_Cfunc_sf_writef_int, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
		_Cgo_use(p1)
		_Cgo_use(p2)
	}
	return
}
//go:cgo_import_static _cgo_75cf4c0ad46f_Cfunc_sf_writef_short
//go:linkname __cgofn__cgo_75cf4c0ad46f_Cfunc_sf_writef_short _cgo_75cf4c0ad46f_Cfunc_sf_writef_short
var __cgofn__cgo_75cf4c0ad46f_Cfunc_sf_writef_short byte
var _cgo_75cf4c0ad46f_Cfunc_sf_writef_short = unsafe.Pointer(&__cgofn__cgo_75cf4c0ad46f_Cfunc_sf_writef_short)

//go:cgo_unsafe_args
func _Cfunc_sf_writef_short(p0 *_Ctype_struct_sf_private_tag, p1 *_Ctype_short, p2 _Ctype_sf_count_t) (r1 _Ctype_sf_count_t) {
	_cgo_runtime_cgocall(_cgo_75cf4c0ad46f_Cfunc_sf_writef_short, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
		_Cgo_use(p1)
		_Cgo_use(p2)
	}
	return
}

//go:cgo_import_static _cgo_75cf4c0ad46f_Cfunc__Cmalloc
//go:linkname __cgofn__cgo_75cf4c0ad46f_Cfunc__Cmalloc _cgo_75cf4c0ad46f_Cfunc__Cmalloc
var __cgofn__cgo_75cf4c0ad46f_Cfunc__Cmalloc byte
var _cgo_75cf4c0ad46f_Cfunc__Cmalloc = unsafe.Pointer(&__cgofn__cgo_75cf4c0ad46f_Cfunc__Cmalloc)

//go:linkname runtime_throw runtime.throw
func runtime_throw(string)

//go:cgo_unsafe_args
func _cgo_cmalloc(p0 uint64) (r1 unsafe.Pointer) {
	_cgo_runtime_cgocall(_cgo_75cf4c0ad46f_Cfunc__Cmalloc, uintptr(unsafe.Pointer(&p0)))
	if r1 == nil {
		runtime_throw("runtime: C malloc failed")
	}
	return
}
