// Code generated by cmd/cgo; DO NOT EDIT.

//line /home/thoth/Developer/scipio/scipio.go:1:1
package scipio

// #cgo pkg-config: sndfile
// #include <stdlib.h>
// #include <sndfile.h>
import _ "unsafe"

import (
	"errors"
	"io"
	"os"
	"reflect"
	"runtime"
	"unsafe"
)

// A sound file. Does not conform to io.Reader.
type File struct {
	s       * /*line :19:11*/_Ctype_SNDFILE /*line :19:20*/
	Format  Info
	virtual *virtualIo // really only necessary to keep a reference so GC doesn't eat it
	fd      uintptr
	closeFd bool
	closed  bool
}

// sErrorType represents a sndfile API error and grabs error description strings from the API.
type sErrorType  /*line :28:17*/_Ctype_int /*line :28:22*/

func (e sErrorType) Error() string {
	return ( /*line :31:9*/_Cfunc_GoString /*line :31:18*/)(( /*line :31:20*/_Cfunc_sf_error_number /*line :31:36*/)( /*line :31:38*/_Ctype_int /*line :31:43*/(e)))
}

// File mode: Read, Write, or ReadWrite
type Mode int

const (
	Read      Mode = ( /*line :38:19*/_Ciconst_SFM_READ /*line :38:28*/)
	Write     Mode = ( /*line :39:19*/_Ciconst_SFM_WRITE /*line :39:29*/)
	ReadWrite Mode = ( /*line :40:19*/_Ciconst_SFM_RDWR /*line :40:28*/)
)

// Info is the struct needed to open a file for reading or writing. When opening a file for reading, everything may generally be left zeroed. The only exception to this is the case of RAW files where the caller has to set the samplerate, channels and format fields to valid values.
type Info struct {
	Frames     int64
	Samplerate int32
	Channels   int32
	Format     Format
	Sections   int32
	Seekable   int32
}

func (i Info) toCinfo() (out * /*line :53:31*/_Ctype_SF_INFO /*line :53:40*/) {
	out = new( /*line :54:12*/_Ctype_SF_INFO /*line :54:21*/) // libsndfile makes a copy of this, safe for GC
	out.frames =  /*line :55:15*/_Ctype_sf_count_t /*line :55:27*/(i.Frames)
	out.samplerate =  /*line :56:19*/_Ctype_int /*line :56:24*/(i.Samplerate)
	out.channels =  /*line :57:17*/_Ctype_int /*line :57:22*/(i.Channels)
	out.format =  /*line :58:15*/_Ctype_int /*line :58:20*/(i.Format)
	out.sections =  /*line :59:17*/_Ctype_int /*line :59:22*/(i.Sections)
	out.seekable =  /*line :60:17*/_Ctype_int /*line :60:22*/(i.Seekable)
	return
}

func fromCinfo(i * /*line :64:19*/_Ctype_SF_INFO /*line :64:28*/) (out Info) {
	out.Frames = int64(i.frames)
	out.Samplerate = int32(i.samplerate)
	out.Channels = int32(i.channels)
	out.Format = Format(i.format)
	out.Sections = int32(i.sections)
	out.Seekable = int32(i.seekable)
	return out
}

// The format field in the above Info structure is made up of the bit-wise OR of a major format type (values between 0x10000 and 0x08000000), a minor format type (with values less than 0x10000) and an optional endian-ness value. The currently understood formats are taken from sndfile.h as follows and also include bitmasks for separating major and minor file types. Not all combinations of endian-ness and major and minor file types are valid.
type Format int32

const (
	SF_FORMAT_WAV   Format = 0x010000 /* Microsoft WAV format (little endian). */
	SF_FORMAT_AIFF  Format = 0x020000 /* Apple/SGI AIFF format (big endian). */
	SF_FORMAT_AU    Format = 0x030000 /* Sun/NeXT AU format (big endian). */
	SF_FORMAT_RAW   Format = 0x040000 /* RAW PCM data. */
	SF_FORMAT_PAF   Format = 0x050000 /* Ensoniq PARIS file format. */
	SF_FORMAT_SVX   Format = 0x060000 /* Amiga IFF / SVX8 / SV16 format. */
	SF_FORMAT_NIST  Format = 0x070000 /* Sphere NIST format. */
	SF_FORMAT_VOC   Format = 0x080000 /* VOC files. */
	SF_FORMAT_IRCAM Format = 0x0A0000 /* Berkeley/IRCAM/CARL */
	SF_FORMAT_W64   Format = 0x0B0000 /* Sonic Foundry's 64 bit RIFF/WAV */
	SF_FORMAT_MAT4  Format = 0x0C0000 /* Matlab (tm) V4.2 / GNU Octave 2.0 */
	SF_FORMAT_MAT5  Format = 0x0D0000 /* Matlab (tm) V5.0 / GNU Octave 2.1 */
	SF_FORMAT_PVF   Format = 0x0E0000 /* Portable Voice Format */
	SF_FORMAT_XI    Format = 0x0F0000 /* Fasttracker 2 Extended Instrument */
	SF_FORMAT_HTK   Format = 0x100000 /* HMM Tool Kit format */
	SF_FORMAT_SDS   Format = 0x110000 /* Midi Sample Dump Standard */
	SF_FORMAT_AVR   Format = 0x120000 /* Audio Visual Research */
	SF_FORMAT_WAVEX Format = 0x130000 /* MS WAVE with WAVEFORMATEX */
	SF_FORMAT_SD2   Format = 0x160000 /* Sound Designer 2 */
	SF_FORMAT_FLAC  Format = 0x170000 /* FLAC lossless file format */
	SF_FORMAT_CAF   Format = 0x180000 /* Core Audio File format */
	SF_FORMAT_WVE   Format = 0x190000 /* Psion WVE format */
	SF_FORMAT_OGG   Format = 0x200000 /* Xiph OGG container */
	SF_FORMAT_MPC2K Format = 0x210000 /* Akai MPC 2000 sampler */
	SF_FORMAT_RF64  Format = 0x220000 /* RF64 WAV file */

	/* Subtypes from here on. */

	SF_FORMAT_PCM_S8 Format = 0x0001 /* Signed 8 bit data */
	SF_FORMAT_PCM_16 Format = 0x0002 /* Signed 16 bit data */
	SF_FORMAT_PCM_24 Format = 0x0003 /* Signed 24 bit data */
	SF_FORMAT_PCM_32 Format = 0x0004 /* Signed 32 bit data */

	SF_FORMAT_PCM_U8 Format = 0x0005 /* Unsigned 8 bit data (WAV and RAW only) */

	SF_FORMAT_FLOAT  Format = 0x0006 /* 32 bit float data */
	SF_FORMAT_DOUBLE Format = 0x0007 /* 64 bit float data */

	SF_FORMAT_ULAW      Format = 0x0010 /* U-Law encoded. */
	SF_FORMAT_ALAW      Format = 0x0011 /* A-Law encoded. */
	SF_FORMAT_IMA_ADPCM Format = 0x0012 /* IMA ADPCM. */
	SF_FORMAT_MS_ADPCM  Format = 0x0013 /* Microsoft ADPCM. */

	SF_FORMAT_GSM610    Format = 0x0020 /* GSM 6.10 encoding. */
	SF_FORMAT_VOX_ADPCM Format = 0x0021 /* Oki Dialogic ADPCM encoding. */

	SF_FORMAT_G721_32 Format = 0x0030 /* 32kbs G721 ADPCM encoding. */
	SF_FORMAT_G723_24 Format = 0x0031 /* 24kbs G723 ADPCM encoding. */
	SF_FORMAT_G723_40 Format = 0x0032 /* 40kbs G723 ADPCM encoding. */

	SF_FORMAT_DWVW_12 Format = 0x0040 /* 12 bit Delta Width Variable Word encoding. */
	SF_FORMAT_DWVW_16 Format = 0x0041 /* 16 bit Delta Width Variable Word encoding. */
	SF_FORMAT_DWVW_24 Format = 0x0042 /* 24 bit Delta Width Variable Word encoding. */
	SF_FORMAT_DWVW_N  Format = 0x0043 /* N bit Delta Width Variable Word encoding. */

	SF_FORMAT_DPCM_8  Format = 0x0050 /* 8 bit differential PCM (XI only) */
	SF_FORMAT_DPCM_16 Format = 0x0051 /* 16 bit differential PCM (XI only) */

	SF_FORMAT_VORBIS Format = 0x0060 /* Xiph Vorbis encoding. */

	/* Endian-ness options. */

	SF_ENDIAN_FILE   Format = 0x00000000 /* Default file endian-ness. */
	SF_ENDIAN_LITTLE Format = 0x10000000 /* Force little endian-ness. */
	SF_ENDIAN_BIG    Format = 0x20000000 /* Force big endian-ness. */
	SF_ENDIAN_CPU    Format = 0x30000000 /* Force CPU endian-ness. */

	SF_FORMAT_SUBMASK  Format = 0x0000FFFF
	SF_FORMAT_TYPEMASK Format = 0x0FFF0000
	SF_FORMAT_ENDMASK  Format = 0x30000000
)

// Open takes a string as a filename, a mode of type Mode (Read, Write, or ReadWrite), and a pointer to an Info struct.

// When opening a file for read, the format field of the Info struct should be set to zero before calling Open(). The only exception to this is the case of RAW files where the caller has to set the samplerate, channels and format fields to valid values. All other fields of the structure are filled in by the library.

//When opening a file for write, the caller must fill in structure members samplerate, channels, and format.

// returns a pointer to the file and a nil error if successful. In case of error, err will be non-nil.
func Open(name string, mode Mode, info *Info) (o *File, err error) {
	if info == nil {
		return nil, errors.New("nil pointer passed to open")
	}
	o = new(File)
	c := ( /*line :162:7*/_Cfunc_CString /*line :162:15*/)(name)
	defer func() func() { _cgo0 := /*line :163:15*/unsafe.Pointer(c); return func() { _cgoCheckPointer(_cgo0, nil); /*line :163:33*/_Cfunc_free(_cgo0); }}()()
	ci := info.toCinfo()
	o.s = ( /*line :165:8*/_Cfunc_sf_open /*line :165:16*/)(c,  /*line :165:21*/_Ctype_int /*line :165:26*/(mode), ci)
	if o.s == nil {
		err = errors.New(( /*line :167:20*/_Cfunc_GoString /*line :167:29*/)(func() *_Ctype_char{ _cgo0 := /*line :167:45*/o.s; _cgoCheckPointer(_cgo0, nil); return /*line :167:49*/_Cfunc_sf_strerror(_cgo0); }()))
	}
	*info = fromCinfo(ci)
	o.Format = *info
	runtime.SetFinalizer(o, (*File).Close)
	return
}

// This probably won't work on windows, because go uses handles instead of integer file descriptors on Windows. Unfortunately I have no way to test.
// The mode and info arguments, and the return values, are the same as for Open().
// close_desc should be true if you want the library to close the file descriptor when you close the sndfile.File object
func OpenFd(fd uintptr, mode Mode, info *Info, close_desc bool) (o *File, err error) {
	if info == nil {
		return nil, errors.New("nil pointer passed to open")
	}
	o = new(File)
	o.closeFd = close_desc
	o.fd = fd
	ci := info.toCinfo()
	o.s = ( /*line :186:8*/_Cfunc_sf_open_fd /*line :186:19*/)( /*line :186:21*/_Ctype_int /*line :186:26*/(fd),  /*line :186:32*/_Ctype_int /*line :186:37*/(mode), ci, 0) // don't want libsndfile to close a Go file object from under us
	if o.s == nil {
		err = errors.New(( /*line :188:20*/_Cfunc_GoString /*line :188:29*/)(func() *_Ctype_char{ _cgo0 := /*line :188:45*/o.s; _cgoCheckPointer(_cgo0, nil); return /*line :188:49*/_Cfunc_sf_strerror(_cgo0); }()))
	}
	*info = fromCinfo(ci)
	o.Format = *info
	runtime.SetFinalizer(o, (*File).Close)
	return
}

// This function allows the caller to check if a set of parameters in the Info struct is valid before calling Open in Write mode.
// FormatCheck returns true if the parameters are valid and false otherwise.
func FormatCheck(i Info) bool {
	return (( /*line :199:10*/_Cfunc_sf_format_check /*line :199:26*/)((* /*line :199:30*/_Ctype_SF_INFO /*line :199:39*/)(unsafe.Pointer(&i))) == ( /*line :199:65*/_Ciconst_SF_TRUE /*line :199:73*/))
}

// Whence args for Seek()
type Whence  /*line :203:13*/_Ctype_int /*line :203:18*/

const (
	Set     Whence = ( /*line :206:19*/_Ciconst_SEEK_SET /*line :206:28*/) // The offset is set to the start of the audio data plus offset (multichannel) frames.
	Current Whence = ( /*line :207:19*/_Ciconst_SEEK_CUR /*line :207:28*/) //The offset is set to its current location plus offset (multichannel) frames.
	End     Whence = ( /*line :208:19*/_Ciconst_SEEK_END /*line :208:28*/) //The offset is set to the end of the data plus offset (multichannel) frames.
)

// The file seek functions work much like lseek in unistd.h with the exception that the non-audio data is ignored and the seek only moves within the audio data section of the file. In addition, seeks are defined in number of (multichannel) frames. Therefore, a seek in a stereo file from the current position forward with an offset of 1 would skip forward by one sample of both channels. This function returns the new offset, and a non-nil error value if unsuccessful
func (f *File) Seek(frames int64, w Whence) (offset int64, err error) {
	r := func() _Ctype_sf_count_t{ _cgo0 := /*line :213:17*/f.s; var _cgo1 _Ctype_sf_count_t = _Ctype_sf_count_t /*line :213:34*/(frames); var _cgo2 _Ctype_int = _Ctype_int /*line :213:49*/(w); _cgoCheckPointer(_cgo0, nil); return /*line :213:53*/_Cfunc_sf_seek(_cgo0, _cgo1, _cgo2); }()
	if r == -1 {
		err = errors.New(( /*line :215:20*/_Cfunc_GoString /*line :215:29*/)(func() *_Ctype_char{ _cgo0 := /*line :215:45*/f.s; _cgoCheckPointer(_cgo0, nil); return /*line :215:49*/_Cfunc_sf_strerror(_cgo0); }()))
	} else {
		offset = int64(r)
	}
	return
}

// The close function closes the file, deallocates its internal buffers and returns a non-nil error value in case of error
func (f *File) Close() (err error) {
	if func() _Ctype_int{ _cgo0 := /*line :224:16*/f.s; _cgoCheckPointer(_cgo0, nil); return /*line :224:20*/_Cfunc_sf_close(_cgo0); }() != 0 {
		err = errors.New(( /*line :225:20*/_Cfunc_GoString /*line :225:29*/)(func() *_Ctype_char{ _cgo0 := /*line :225:45*/f.s; _cgoCheckPointer(_cgo0, nil); return /*line :225:49*/_Cfunc_sf_strerror(_cgo0); }()))
	}
	if f.closeFd {
		nf := os.NewFile(f.fd, "")
		err = nf.Close()
	}
	runtime.SetFinalizer(f, nil)
	return
}

// If the file is opened Write or ReadWrite, call the operating system's function to force the writing of all file cache buffers to disk. If the file is opened Read no action is taken.
func (f *File) WriteSync() {
	func() { _cgo0 := /*line :237:18*/f.s; _cgoCheckPointer(_cgo0, nil); /*line :237:22*/_Cfunc_sf_write_sync(_cgo0); }()
}

/*
The file read items functions fill the array pointed to by out with the requested number of items. The length of out must be a product of the number of channels or an error will occur.

	It is important to note that the data type used by the calling program and the data format of the file do not need to be the same. For instance, it is possible to open a 16 bit PCM encoded WAV file and read the data into a slice of floats. The library seamlessly converts between the two formats on-the-fly. See Note 1.

	Returns the number of items read. Unless the end of the file was reached during the read, the return value should equal the number of items requested. Attempts to read beyond the end of the file will not result in an error but will cause ReadItems to return less than the number of items requested or 0 if already at the end of the file.

	out must be a slice or array of int, int16, int32, float32, or float64.
*/
func (f *File) ReadItems(out interface{}) (read int64, err error) {
	t := reflect.TypeOf(out)
	if t.Kind() != reflect.Array && t.Kind() != reflect.Slice {
		return -1, errors.New("You need to give me an array!")
	}

	v := reflect.ValueOf(out)
	l := v.Len()
	o := v.Slice(0, l)
	var n  /*line :258:8*/_Ctype_sf_count_t /*line :258:20*/
	switch t.Elem().Kind() {
	case reflect.Int16:
		n = func() _Ctype_sf_count_t{ _cgo0 := /*line :261:23*/f.s; var _cgo1 *_Ctype_short = /*line :261:28*/(*_Ctype_short /*line :261:37*/)(unsafe.Pointer(o.Index(0).Addr().Pointer())); var _cgo2 _Ctype_sf_count_t = _Ctype_sf_count_t /*line :261:97*/(l); _cgoCheckPointer(_cgo0, nil); return /*line :261:101*/_Cfunc_sf_read_short(_cgo0, _cgo1, _cgo2); }()
	case reflect.Int32:
		n = func() _Ctype_sf_count_t{ _cgo0 := /*line :263:21*/f.s; var _cgo1 *_Ctype_int = /*line :263:26*/(*_Ctype_int /*line :263:33*/)(unsafe.Pointer(o.Index(0).Addr().Pointer())); var _cgo2 _Ctype_sf_count_t = _Ctype_sf_count_t /*line :263:93*/(l); _cgoCheckPointer(_cgo0, nil); return /*line :263:97*/_Cfunc_sf_read_int(_cgo0, _cgo1, _cgo2); }()
	case reflect.Float32:
		n = func() _Ctype_sf_count_t{ _cgo0 := /*line :265:23*/f.s; var _cgo1 *_Ctype_float = /*line :265:28*/(*_Ctype_float /*line :265:37*/)(unsafe.Pointer(o.Index(0).Addr().Pointer())); var _cgo2 _Ctype_sf_count_t = _Ctype_sf_count_t /*line :265:97*/(l); _cgoCheckPointer(_cgo0, nil); return /*line :265:101*/_Cfunc_sf_read_float(_cgo0, _cgo1, _cgo2); }()
	case reflect.Float64:
		n = func() _Ctype_sf_count_t{ _cgo0 := /*line :267:24*/f.s; var _cgo1 *_Ctype_double = /*line :267:29*/(*_Ctype_double /*line :267:39*/)(unsafe.Pointer(o.Index(0).Addr().Pointer())); var _cgo2 _Ctype_sf_count_t = _Ctype_sf_count_t /*line :267:99*/(l); _cgoCheckPointer(_cgo0, nil); return /*line :267:103*/_Cfunc_sf_read_double(_cgo0, _cgo1, _cgo2); }()
	case reflect.Int:
		switch t.Bits() {
		case 32:
			n = func() _Ctype_sf_count_t{ _cgo0 := /*line :271:22*/f.s; var _cgo1 *_Ctype_int = /*line :271:27*/(*_Ctype_int /*line :271:34*/)(unsafe.Pointer(o.Index(0).Addr().Pointer())); var _cgo2 _Ctype_sf_count_t = _Ctype_sf_count_t /*line :271:94*/(l); _cgoCheckPointer(_cgo0, nil); return /*line :271:98*/_Cfunc_sf_read_int(_cgo0, _cgo1, _cgo2); }()
		case 16: // doubtful
			n = func() _Ctype_sf_count_t{ _cgo0 := /*line :273:24*/f.s; var _cgo1 *_Ctype_short = /*line :273:29*/(*_Ctype_short /*line :273:38*/)(unsafe.Pointer(o.Index(0).Addr().Pointer())); var _cgo2 _Ctype_sf_count_t = _Ctype_sf_count_t /*line :273:98*/(l); _cgoCheckPointer(_cgo0, nil); return /*line :273:102*/_Cfunc_sf_read_short(_cgo0, _cgo1, _cgo2); }()
		default:
			err = errors.New("Unsupported type in read buffer, needs (u)int16, (u)int32, or float type")
		}
	default:
		err = errors.New("Unsupported type in read buffer, needs (u)int16, (u)int32, or float type")
	}
	if err != nil {
		read = -1
		return
	}

	read = int64(n)
	if read < 0 {
		err = errors.New(( /*line :287:20*/_Cfunc_GoString /*line :287:29*/)(func() *_Ctype_char{ _cgo0 := /*line :287:45*/f.s; _cgoCheckPointer(_cgo0, nil); return /*line :287:49*/_Cfunc_sf_strerror(_cgo0); }()))
	}
	return
}

/*
The file read frames functions fill the array pointed to by out with the requested number of frames of data. The array must be large enough to hold the product of frames and the number of channels.

	The sf_readf_XXXX functions return the number of frames read. Unless the end of the file was reached during the read, the return value should equal the number of frames requested. Attempts to read beyond the end of the file will not result in an error but will cause the sf_readf_XXXX functions to return less than the number of frames requested or 0 if already at the end of the file.
*/
func (f *File) ReadFrames(out interface{}) (read int64, err error) {
	t := reflect.TypeOf(out)
	if t.Kind() != reflect.Array && t.Kind() != reflect.Slice {
		return -1, errors.New("You need to give me an array!")
	}

	v := reflect.ValueOf(out)
	l := v.Len()
	o := v.Slice(0, l)
	frames := l / int(f.Format.Channels)
	if frames < 1 {
		err = io.EOF
		return
	}
	var n  /*line :311:8*/_Ctype_sf_count_t /*line :311:20*/
	p := unsafe.Pointer(o.Index(0).Addr().Pointer())
	switch t.Elem().Kind() {
	case reflect.Int16, reflect.Uint16:
		n = func() _Ctype_sf_count_t{ _cgo0 := /*line :315:24*/f.s; var _cgo1 *_Ctype_short = /*line :315:29*/(*_Ctype_short /*line :315:38*/)(p); var _cgo2 _Ctype_sf_count_t = _Ctype_sf_count_t /*line :315:56*/(frames); _cgoCheckPointer(_cgo0, nil); return /*line :315:65*/_Cfunc_sf_readf_short(_cgo0, _cgo1, _cgo2); }()
	case reflect.Int32, reflect.Uint32:
		n = func() _Ctype_sf_count_t{ _cgo0 := /*line :317:22*/f.s; var _cgo1 *_Ctype_int = /*line :317:27*/(*_Ctype_int /*line :317:34*/)(p); var _cgo2 _Ctype_sf_count_t = _Ctype_sf_count_t /*line :317:52*/(frames); _cgoCheckPointer(_cgo0, nil); return /*line :317:61*/_Cfunc_sf_readf_int(_cgo0, _cgo1, _cgo2); }()
	case reflect.Float32:
		n = func() _Ctype_sf_count_t{ _cgo0 := /*line :319:24*/f.s; var _cgo1 *_Ctype_float = /*line :319:29*/(*_Ctype_float /*line :319:38*/)(p); var _cgo2 _Ctype_sf_count_t = _Ctype_sf_count_t /*line :319:56*/(frames); _cgoCheckPointer(_cgo0, nil); return /*line :319:65*/_Cfunc_sf_readf_float(_cgo0, _cgo1, _cgo2); }()
	case reflect.Float64:
		n = func() _Ctype_sf_count_t{ _cgo0 := /*line :321:25*/f.s; var _cgo1 *_Ctype_double = /*line :321:30*/(*_Ctype_double /*line :321:40*/)(p); var _cgo2 _Ctype_sf_count_t = _Ctype_sf_count_t /*line :321:58*/(frames); _cgoCheckPointer(_cgo0, nil); return /*line :321:67*/_Cfunc_sf_readf_double(_cgo0, _cgo1, _cgo2); }()
	case reflect.Int, reflect.Uint:
		switch t.Bits() {
		case 32:
			n = func() _Ctype_sf_count_t{ _cgo0 := /*line :325:23*/f.s; var _cgo1 *_Ctype_int = /*line :325:28*/(*_Ctype_int /*line :325:35*/)(p); var _cgo2 _Ctype_sf_count_t = _Ctype_sf_count_t /*line :325:53*/(frames); _cgoCheckPointer(_cgo0, nil); return /*line :325:62*/_Cfunc_sf_readf_int(_cgo0, _cgo1, _cgo2); }()
		case 16: // doubtful
			n = func() _Ctype_sf_count_t{ _cgo0 := /*line :327:25*/f.s; var _cgo1 *_Ctype_short = /*line :327:30*/(*_Ctype_short /*line :327:39*/)(p); var _cgo2 _Ctype_sf_count_t = _Ctype_sf_count_t /*line :327:57*/(frames); _cgoCheckPointer(_cgo0, nil); return /*line :327:66*/_Cfunc_sf_readf_short(_cgo0, _cgo1, _cgo2); }()
		default:
			err = errors.New("Unsupported type in read buffer, needs (u)int16, (u)int32, or float type")
		}
	default:
		err = errors.New("Unsupported type in read buffer, needs (u)int16, (u)int32, or float type")
	}
	if err != nil {
		read = -1
		return
	}

	read = int64(n)
	if read < 0 {
		err = errors.New(( /*line :341:20*/_Cfunc_GoString /*line :341:29*/)(func() *_Ctype_char{ _cgo0 := /*line :341:45*/f.s; _cgoCheckPointer(_cgo0, nil); return /*line :341:49*/_Cfunc_sf_strerror(_cgo0); }()))
	}
	return
}

type StringType  /*line :346:17*/_Ctype_int /*line :346:22*/

const (
	Title       StringType = ( /*line :349:27*/_Ciconst_SF_STR_TITLE /*line :349:40*/)
	Copyright   StringType = ( /*line :350:27*/_Ciconst_SF_STR_COPYRIGHT /*line :350:44*/)
	Software    StringType = ( /*line :351:27*/_Ciconst_SF_STR_SOFTWARE /*line :351:43*/)
	Artist      StringType = ( /*line :352:27*/_Ciconst_SF_STR_ARTIST /*line :352:41*/)
	Comment     StringType = ( /*line :353:27*/_Ciconst_SF_STR_COMMENT /*line :353:42*/)
	Date        StringType = ( /*line :354:27*/_Ciconst_SF_STR_DATE /*line :354:39*/)
	Album       StringType = ( /*line :355:27*/_Ciconst_SF_STR_ALBUM /*line :355:40*/)
	License     StringType = ( /*line :356:27*/_Ciconst_SF_STR_LICENSE /*line :356:42*/)
	Tracknumber StringType = ( /*line :357:27*/_Ciconst_SF_STR_TRACKNUMBER /*line :357:46*/)
	Genre       StringType = ( /*line :358:27*/_Ciconst_SF_STR_GENRE /*line :358:40*/)
	First       StringType = ( /*line :359:27*/_Ciconst_SF_STR_FIRST /*line :359:40*/)
	Last        StringType = ( /*line :360:27*/_Ciconst_SF_STR_LAST /*line :360:39*/)
)

// The GetString() method returns the specified string if it exists and a NULL pointer otherwise. In addition to the string ids above, First (== Title) and Last (always the same as the highest numbers string id) are also available to allow iteration over all the available string ids.
func (f *File) GetString(typ StringType) (out string) {
	// although it's not clear from the docs, sf_get_string doesn't require you to free the string that is returned
	s := func() *_Ctype_char{ _cgo0 := /*line :366:23*/f.s; var _cgo1 _Ctype_int = _Ctype_int /*line :366:33*/(typ); _cgoCheckPointer(_cgo0, nil); return /*line :366:39*/_Cfunc_sf_get_string(_cgo0, _cgo1); }()
	if s != nil {
		out = ( /*line :368:9*/_Cfunc_GoString /*line :368:18*/)(s)
	}
	return
}

// The SetString() method sets the string data in a file. It returns nil on success and non-nil on error.
func (f *File) SetString(in string, typ StringType) (err error) {
	s := ( /*line :375:7*/_Cfunc_CString /*line :375:15*/)(in)
	defer func() func() { _cgo0 := /*line :376:15*/unsafe.Pointer(s); return func() { _cgoCheckPointer(_cgo0, nil); /*line :376:33*/_Cfunc_free(_cgo0); }}()()
	if func() _Ctype_int{ _cgo0 := /*line :377:21*/f.s; var _cgo1 _Ctype_int = _Ctype_int /*line :377:31*/(typ); var _cgo2 *_Ctype_char = /*line :377:38*/s; _cgoCheckPointer(_cgo0, nil); return /*line :377:40*/_Cfunc_sf_set_string(_cgo0, _cgo1, _cgo2); }() != 0 {
		err = errors.New(( /*line :378:20*/_Cfunc_GoString /*line :378:29*/)(func() *_Ctype_char{ _cgo0 := /*line :378:45*/f.s; _cgoCheckPointer(_cgo0, nil); return /*line :378:49*/_Cfunc_sf_strerror(_cgo0); }()))
	}
	return
}

//The file write items function writes the data in the array or slice in the input argument to the file. The length of the slice must be an integer product of the number of channels or an error will occur.
//
//It is important to note that the data type used by the calling program and the data format of the file do not need to be the same. For instance, it is possible to open a 16 bit PCM encoded WAV file and write the data from a []float32. The library seamlessly converts between the two formats on-the-fly.
//
//Returns the number of items written (which should be the same as the length of the input parameter). err will be nil, except in case of failure

func (f *File) WriteItems(in interface{}) (written int64, err error) {
	t := reflect.TypeOf(in)
	if t.Kind() != reflect.Array && t.Kind() != reflect.Slice {
		errors.New("You need to give me an array!")
	}

	v := reflect.ValueOf(in)
	l := v.Len()
	o := v.Slice(0, l)
	var n  /*line :398:8*/_Ctype_sf_count_t /*line :398:20*/
	p := unsafe.Pointer(o.Index(0).Addr().Pointer())
	switch t.Elem().Kind() {
	case reflect.Int16, reflect.Uint16:
		n = func() _Ctype_sf_count_t{ _cgo0 := /*line :402:24*/f.s; var _cgo1 *_Ctype_short = /*line :402:29*/(*_Ctype_short /*line :402:38*/)(p); var _cgo2 _Ctype_sf_count_t = _Ctype_sf_count_t /*line :402:56*/(l); _cgoCheckPointer(_cgo0, nil); return /*line :402:60*/_Cfunc_sf_write_short(_cgo0, _cgo1, _cgo2); }()
	case reflect.Int32, reflect.Uint32:
		n = func() _Ctype_sf_count_t{ _cgo0 := /*line :404:22*/f.s; var _cgo1 *_Ctype_int = /*line :404:27*/(*_Ctype_int /*line :404:34*/)(p); var _cgo2 _Ctype_sf_count_t = _Ctype_sf_count_t /*line :404:52*/(l); _cgoCheckPointer(_cgo0, nil); return /*line :404:56*/_Cfunc_sf_write_int(_cgo0, _cgo1, _cgo2); }()
	case reflect.Float32:
		n = func() _Ctype_sf_count_t{ _cgo0 := /*line :406:24*/f.s; var _cgo1 *_Ctype_float = /*line :406:29*/(*_Ctype_float /*line :406:38*/)(p); var _cgo2 _Ctype_sf_count_t = _Ctype_sf_count_t /*line :406:56*/(l); _cgoCheckPointer(_cgo0, nil); return /*line :406:60*/_Cfunc_sf_write_float(_cgo0, _cgo1, _cgo2); }()
	case reflect.Float64:
		n = func() _Ctype_sf_count_t{ _cgo0 := /*line :408:25*/f.s; var _cgo1 *_Ctype_double = /*line :408:30*/(*_Ctype_double /*line :408:40*/)(p); var _cgo2 _Ctype_sf_count_t = _Ctype_sf_count_t /*line :408:58*/(l); _cgoCheckPointer(_cgo0, nil); return /*line :408:62*/_Cfunc_sf_write_double(_cgo0, _cgo1, _cgo2); }()
	case reflect.Int, reflect.Uint:
		switch t.Bits() {
		case 32:
			n = func() _Ctype_sf_count_t{ _cgo0 := /*line :412:23*/f.s; var _cgo1 *_Ctype_int = /*line :412:28*/(*_Ctype_int /*line :412:35*/)(p); var _cgo2 _Ctype_sf_count_t = _Ctype_sf_count_t /*line :412:53*/(l); _cgoCheckPointer(_cgo0, nil); return /*line :412:57*/_Cfunc_sf_write_int(_cgo0, _cgo1, _cgo2); }()
		case 16: // doubtful
			n = func() _Ctype_sf_count_t{ _cgo0 := /*line :414:25*/f.s; var _cgo1 *_Ctype_short = /*line :414:30*/(*_Ctype_short /*line :414:39*/)(p); var _cgo2 _Ctype_sf_count_t = _Ctype_sf_count_t /*line :414:57*/(l); _cgoCheckPointer(_cgo0, nil); return /*line :414:61*/_Cfunc_sf_write_short(_cgo0, _cgo1, _cgo2); }()
		default:
			err = errors.New("Unsupported type in read buffer, needs (u)int16, (u)int32, or float type")
		}
	default:
		err = errors.New("Unsupported type in read buffer, needs (u)int16, (u)int32, or float type")
	}
	if err != nil {
		written = -1
		return
	}

	written = int64(n)
	if int(n) != l {
		err = errors.New(( /*line :428:20*/_Cfunc_GoString /*line :428:29*/)(func() *_Ctype_char{ _cgo0 := /*line :428:45*/f.s; _cgoCheckPointer(_cgo0, nil); return /*line :428:49*/_Cfunc_sf_strerror(_cgo0); }()))
	}
	return
}

// The file write frames function writes the data in the array or slice pointed to by the input argument to the file. The items parameter must be an integer product of the number of channels or an error will occur.
//
// It is important to note that the data type used by the calling program and the data format of the file do not need to be the same. For instance, it is possible to open a 16 bit PCM encoded WAV file and write the data from a []float32. The library seamlessly converts between the two formats on-the-fly.
//
// Returns the number of frames written (which should be the same as the length of the input parameter divided by the number of channels). err wil be nil except in case of failure
func (f *File) WriteFrames(in interface{}) (written int64, err error) {
	t := reflect.TypeOf(in)
	if t.Kind() != reflect.Array && t.Kind() != reflect.Slice {
		errors.New("You need to give me an array!")
	}

	v := reflect.ValueOf(in)
	l := v.Len()
	o := v.Slice(0, l)
	frames := l / int(f.Format.Channels)
	if frames < 1 {
		err = io.EOF
		return
	}
	var n  /*line :452:8*/_Ctype_sf_count_t /*line :452:20*/
	p := unsafe.Pointer(o.Index(0).Addr().Pointer())
	switch t.Elem().Kind() {
	case reflect.Int16, reflect.Uint16:
		n = func() _Ctype_sf_count_t{ _cgo0 := /*line :456:25*/f.s; var _cgo1 *_Ctype_short = /*line :456:30*/(*_Ctype_short /*line :456:39*/)(p); var _cgo2 _Ctype_sf_count_t = _Ctype_sf_count_t /*line :456:57*/(frames); _cgoCheckPointer(_cgo0, nil); return /*line :456:66*/_Cfunc_sf_writef_short(_cgo0, _cgo1, _cgo2); }()
	case reflect.Int32, reflect.Uint32:
		n = func() _Ctype_sf_count_t{ _cgo0 := /*line :458:23*/f.s; var _cgo1 *_Ctype_int = /*line :458:28*/(*_Ctype_int /*line :458:35*/)(p); var _cgo2 _Ctype_sf_count_t = _Ctype_sf_count_t /*line :458:53*/(frames); _cgoCheckPointer(_cgo0, nil); return /*line :458:62*/_Cfunc_sf_writef_int(_cgo0, _cgo1, _cgo2); }()
	case reflect.Float32:
		n = func() _Ctype_sf_count_t{ _cgo0 := /*line :460:25*/f.s; var _cgo1 *_Ctype_float = /*line :460:30*/(*_Ctype_float /*line :460:39*/)(p); var _cgo2 _Ctype_sf_count_t = _Ctype_sf_count_t /*line :460:57*/(frames); _cgoCheckPointer(_cgo0, nil); return /*line :460:66*/_Cfunc_sf_writef_float(_cgo0, _cgo1, _cgo2); }()
	case reflect.Float64:
		n = func() _Ctype_sf_count_t{ _cgo0 := /*line :462:26*/f.s; var _cgo1 *_Ctype_double = /*line :462:31*/(*_Ctype_double /*line :462:41*/)(p); var _cgo2 _Ctype_sf_count_t = _Ctype_sf_count_t /*line :462:59*/(frames); _cgoCheckPointer(_cgo0, nil); return /*line :462:68*/_Cfunc_sf_writef_double(_cgo0, _cgo1, _cgo2); }()
	case reflect.Int, reflect.Uint:
		switch t.Bits() {
		case 32:
			n = func() _Ctype_sf_count_t{ _cgo0 := /*line :466:24*/f.s; var _cgo1 *_Ctype_int = /*line :466:29*/(*_Ctype_int /*line :466:36*/)(p); var _cgo2 _Ctype_sf_count_t = _Ctype_sf_count_t /*line :466:54*/(frames); _cgoCheckPointer(_cgo0, nil); return /*line :466:63*/_Cfunc_sf_writef_int(_cgo0, _cgo1, _cgo2); }()
		case 16: // doubtful
			n = func() _Ctype_sf_count_t{ _cgo0 := /*line :468:26*/f.s; var _cgo1 *_Ctype_short = /*line :468:31*/(*_Ctype_short /*line :468:40*/)(p); var _cgo2 _Ctype_sf_count_t = _Ctype_sf_count_t /*line :468:58*/(frames); _cgoCheckPointer(_cgo0, nil); return /*line :468:67*/_Cfunc_sf_writef_short(_cgo0, _cgo1, _cgo2); }()
		default:
			err = errors.New("Unsupported type in written buffer, needs (u)int16, (u)int32, or float type")
		}
	default:
		err = errors.New("Unsupported type in written buffer, needs (u)int16, (u)int32, or float type")
	}
	if err != nil {
		written = -1
		return
	}

	written = int64(n)
	if int(n) != frames {
		err = errors.New(( /*line :482:20*/_Cfunc_GoString /*line :482:29*/)(func() *_Ctype_char{ _cgo0 := /*line :482:45*/f.s; _cgoCheckPointer(_cgo0, nil); return /*line :482:49*/_Cfunc_sf_strerror(_cgo0); }()))
	}
	return
}
